### PR TITLE
fix #37

### LINKED ISSUE #37: runtime.StyleParamWithLocation for map[string]int fails with "map not of type map[string]interface{}"
```
# spec
    PriorityFilter:
      name: priority
      in: query
      schema:
        type: object
        additionalProperties:
          type: integer
```

```
// models 

// PriorityFilter defines model for PriorityFilter.
type PriorityFilter map[string]int

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Priority *PriorityFilter `form:"priority,omitempty" json:"priority,omitempty"`
}
```

```
// using client

pf := PriorityFilter(map[string]int{"gt": 100})
_, err := client.GetMessages(ctx, &GetMessagesParams{
	Priority: &pf,
})
if err != nil {
	t.Fatalf("get messages: %s", err)
}

// fails with error: get messages: map not of type map[string]interface{}
```
It fails on call `if queryFrag, err := runtime.StyleParamWithLocation("form", true, "priority", runtime.ParamLocationQuery, *params.Priority); err != nil {
				return nil, err
			}`

### PR DESCRIPTION
**Pull request by andnow873**
Explicitly build `map[string]any` in `StyleParamWithLocation`

### CODE REVIEW

File: styleparam.go [hunk 1]
```diff
@@ -97,7 +97,12 @@ func StyleParamWithLocation(style string, explode bool, paramName string, paramL
 	case reflect.Struct:
 		return styleStruct(style, explode, paramName, paramLocation, value)
 	case reflect.Map:
-		return styleMap(style, explode, paramName, paramLocation, value)
+		dict := make(map[string]any, v.Len())
+		for _, key := range v.MapKeys() {
+			// the key is guaranteed to be a string
+			dict[key.String()] = v.MapIndex(key).Interface()
+		}
+		return styleMap(style, explode, paramName, paramLocation, dict)
```
Comment (mromaszewicz) [inline styleparam.go:105]: Thank you for doing this, but I think that styleMap should have some generic map iteration code instead of adapting the map in this location. It'll be more robust. `styleMap` doesn't depend on the types themselves, because it calls a type-aware formatting function, so all it needs to do is unwind the map in a generic way.

**Review by mromaszewicz — CHANGES_REQUESTED** [review]

**Review by mromaszewicz — APPROVED** [review]
